package com.core_sur.finals;

public interface ParamFinals {
int STATISTICAL_START=1; //启动
int STATISTICAL_REQUESTADS=2; //请求一条广告
int STATISTICAL_END=3; //请求一条广告
int STATISTICAL_SHOWADS=4; //成功展示一条广告
int STATISTICAL_CLICKADS=6; //成功点击一条广告
int STATISTICAL_REQUESTWARE=7;
int STATISTICAL_WARESUCCESS=8;
int STATISTICAL_WAREFAIL=9;
int STATISTICAL_REQUESTPOINT=10;
int STATISTICAL_DEDUCTPOINT=10;
int STATISTICAL_ADDPOINT=11;
int MODE_POINT = 2;
int MODE_FLOAT = 1;
}
